### ISSUE TITLE
Remove shared-modules

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/com.leinardi.gx52#1]
I noticed it's a leftover from libusb that isn't used anymore few seconds after merging

**Comment by leinardi** [comment]
I'm still using shared modules for libappindicator:
```
shared-modules/libappindicator/libappindicator-gtk3-introspection-12.10.json
```

BTW, I find really difficult to navigate the modules when they are all in a single file so I'd like to split them in separate one like I have in all my apps (I know that for you makes the review easier when they are as they are now, but hope you won't mind if I change them back now).

**Comment by bilelmoussaoui** [comment]
Oh never mind then :) 

> BTW, I find really difficult to navigate the modules when they are all in a single file so I'd like to split them in separate one like I have in all my apps (I know that for you makes the review easier when they are as they are now, but hope you won't mind if I change them back now).

There are no strict rules about that and there won't be any. It's your application and you're free to write the manifest in whatever is easier for you. There are mostly conventions to make it's easier for the community to collaborate
